# Site settings
title: Alex Carpenter
email: your-email@domain.com
description: >
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/material-jekyll-theme"
url: "http://alexcarpenter.me"
fixedNav: 'true' # true or false
theme: purple # green, blue, orange, purple, grey
twitterUsername: jekyllrb
githubUsername:  jekyll

# Build settings
markdown: kramdown
include: [_pages]
exclude: [_site]
sass:
  style: compressed
