# Site settings
title: Binary Horizons Blog
email: almero.steyn@qdelft.nl
description: >
  A blog from a diehard frontend and a11y fan.
baseurl: ""
url: "http://almerosteyn.github.io"
fixedNav: 'true' # true or false
theme: minima # green, blue, orange, purple, grey
twitterUsername: kryptos_rsa
githubUsername: AlmeroSteyn
dribbbleUsername:
codepenUsername:

# Build settings
permalink: /:year/:month/:title
markdown: kramdown
include: [_pages]
comments: true
# highlighter: pygments
# port: 8889
exclude: [_site, CHANGELOG.md, LICENSE, README.md]
sass:
  style: compressed
gems:
  - jekyll-sitemap
